#!/bin/bash
set -Eeou pipefail

# For Podman
if [ ! -d $XDG_RUNTIME_DIR ]; then
    mkdir -p $XDG_RUNTIME_DIR
fi

# Check for missing connections on supported interfaces
PLUGS=(removable-media ssh-keys adb-support docker etc-gitconfig)
MISSING_CONNECTION=()

for plug in "${PLUGS[@]}"; do
    if ! snapctl is-connected "${plug}"; then
        MISSING_CONNECTION+=("${plug}")
    fi
done

if [ ${#MISSING_CONNECTION[*]} -gt 0 ]; then
    echo "Missing connection(s). You can add connection(s) manually by running:"

    for connection in "${MISSING_CONNECTION[@]}"; do
        echo "sudo snap connect clickable:${connection}"
    done
fi

# Run Clickable
export PATH=${SNAP}/usr/lib/git-core/:${PATH}
exec "$@"
