stages:
  - test
  - publish

integration-test:
  stage: test
  image: clickable/testing
  script:
    - nosetests integration

unit-test:
  stage: test
  image: clickable/testing
  script:
    - nosetests unit

check-template-names:
  stage: test
  image: clickable/testing
  script:
    - tests/check-template-names.py
  allow_failure: true

publish-pypi:
  stage: publish
  image: clickable/build-deb:focal
  only:
    - tags
  script:
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload dist/*
