name: clickable
version: '1.0.1'
summary: Compile, build, and deploy click packages from the cli
description: |
  Replace the Ubuntu IDE with clickable and streamline your
  click development process.
  For more info, read the docs: https://github.com/bhdouglass/clickable
  In order for clickable to work you must have lxd already setup
  and have the usdk tools installed.

grade: stable
confinement: classic

apps:
  clickable:
    command: clickable
  usdk-target:
    command: usdk-target.wrapper

parts:
  clickable:
    plugin: dump
    source: https://github.com/bhdouglass/clickable.git
    stage-packages:
      - python
