name: clickable
version: '2.1.4'
summary: Compile, build, and deploy click packages from the cli
description: |
  Replace the Ubuntu IDE with clickable and streamline your
  click development process.
  For more info, read the docs: http://clickable.bhdouglass.com/en/latest/
  In order for clickable to work you must have docker already setup.

grade: stable
confinement: classic

apps:
  clickable:
    command: clickable

parts:
  clickable:
    plugin: dump
    source: https://github.com/bhdouglass/clickable.git
    stage-packages:
      - python
